[package]
name = "pixiekit-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Core library for Pixiekit asset preparation toolkit"

[dependencies]
image = { workspace = true }
walkdir = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
